### ISSUE TITLE
[DataCap Application] KABAT - FBSnor

### ISSUE THREAD

**Issue by FILDCKabat** [filecoin-project/filecoin-plus-large-datasets#1596]
### Data Owner Name

Flexible Building System Norway AS

### Data Owner Country/Region

Norway

### Data Owner Industry

Construction, Property & Real Estate

### Website

https://fbsnor.no/

### Social Media

```text
https://www.facebook.com/fbsnor.no/
https://www.linkedin.com/company/flexible-building-system-norway/
```

### Total amount of DataCap being requested

1PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1nt3mihrazsft66v6zgcyru2k45i3kjdufwujkia

### Custom multisig

- [x] Use Custom Multisig

### Identifier

efil

### Share a brief history of your project and organization

```text
Flexible Building System Norway AS exist for a few years on a Scandinavian market, but owners and core employees are in a branch for over 20 Years. That's how their experience and knowledge come in a different type of buildings. 
FBS has their own design team. They do projects and visualizations themself, the same as manufacturing and assembly documentation. 
They do always buildings suit into customers needs, they underline it even in their name. Thanks to experienced team they are able to give flexible (part of the company name) and safe solutions.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Design documentation, presentations, visualizations, and big part are pictures and movies as they do 100% movie documentation while building erection. 
This is an application for E-FIL+.
```

### Where was the data currently stored in this dataset sourced from

Google Cloud

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
together with SP
```

### Please share a sample of the data

```text
https://www.linkedin.com/feed/update/urn:li:activity:6754305334065561600/
https://www.facebook.com/fbsnor.no/videos/2466709930300704
https://www.facebook.com/watch/?v=538998936997094
https://www.finn.no/realestate/businesssale/ad.html?finnkode=270044341&ci=6
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
FBS is going to store original design files which are not for public access. This is company know how and critical data.
```

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

North America, Europe, Asia, Australia (continent)

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```
f02033496, f01771403 | Netherlands | EU | DCENT
f01127678 | Poland | EU | FILDC 
f0198**** | USA | GREATERHEAT |
f0188**** | Singapore | ASIA | GREATERHEAT |
f01885088, f01989888, f01926635, f01933917, f02058048 | Hong Kong | ASIA | Hong Kong Morpho Technology Limited
f01967501, f01969323, f01908671, f01967501 | USA | acrontech.us
f08240, f0187709, f01222595 | Russia | ASIA| Shekelme
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you please fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by FILDCKabat** [comment]
done

**Comment by kevzak** [comment]
This application is awaiting KYB completion. Also it needs updated SP storage list: SP ID, Business Name, Location

**Comment by FILDCKabat** [comment]
I will check with customer tomorrow, He was going to manage it a week ago

**Comment by FILDCKabat** [comment]
> **Thanks for your request!**
> 
> ```
> Heads up, you’re requesting more than the typical weekly onboarding rate of DataCap!
> ```

should we rediscussed it?

**Comment by kevzak** [comment]
> > **Thanks for your request!**
> > ```
> > Heads up, you’re requesting more than the typical weekly onboarding rate of DataCap!
> > ```
> 
> should we rediscussed it?

this is a message from the bot, do not worry here

**Comment by FILDCKabat** [comment]
ok :)

**Comment by FILDCKabat** [comment]
@kevzak 
got an information from a customer that KYB is done

**Comment by kevzak** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 200TiB
#### Client address
> f1ieughpsgkdynelb2tipfpuhdvcvltfvsuv54q2q

**Comment by kevzak** [comment]
Hello, I can confirm that @FILDCKabat  and FBSnor have complete the E-Fil+ KYC and KYB checks successfully via the Synaps.io product.

We will now randomly assign notaries for first allocation review. Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@OlivierMolenkamp
@BobbyChoii

Please review Client, Data, SP details and leave a comment as needed. Please comment by March 10th. Thanks! If you are not interested in signing please also leave a comment stating why. Thanks!

**Comment by FILDCKabat** [comment]
@kevzak pls add new Notaries

**Comment by kevzak** [comment]
@OlivierMolenkamp
@BobbyChoii
did not hear back from you about your assigned review.

We will move forward and randomly assign
@jamerduhgamer
@PluskitOfficial

Please review Client, Data, SP details and leave a comment as needed. Please comment by March 15th. If you are not interested in signing please also leave a comment stating why. Thanks!

**Comment by jamerduhgamer** [comment]
We can confirm that the client is reputable through their participation at ESPA and having met them in person. We are willing to support this data and the selected SPs are fine with us as they are with 4 different entities and spread across two continents.

**Comment by kevzak** [comment]
> We can confirm that the client is reputable through their participation at ESPA and having met them in person. We are willing to support this data and the selected SPs are fine with us as they are with 4 different entities and spread across two continents.

@jamerduhgamer does that mean you are signing?

**Comment by liyunzhi-666** [comment]
Based on the comments in the issue and application, I'm willing to support the first round and look forward to the follow-up.

**Comment by liyunzhi-666** [comment]
![image](https://user-images.githubusercontent.com/52949274/226224989-e18b8fb4-a661-4126-aa57-a09a36c0eff0.png)
There is no application for #1596 in the back office. @fabriziogianni7 
cc @kevzak

**Comment by fabriziogianni7** [comment]
I think the problem is that labels are changed and the issue need some review
@simonkim0515

**Comment by simonkim0515** [comment]
@liyunzhi-666 Should be fixed now

**Comment by liyunzhi-666** [comment]
After modifying the tag, it still can't be found. @simonkim0515 
![image](https://user-images.githubusercontent.com/52949274/226502940-84a0663c-f4db-4e99-865d-3479c2cfecd1.png)

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebereg5j3b6w2eldu3n6q23wx7cpvrgjxvaj3lzn2tr34cu2lphoc 
#### Address 
> f12adedmfbdzq52hwlhzjfas35xo5g65jfxd4ousy
#### Datacap Allocated
> 51.19TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebereg5j3b6w2eldu3n6q23wx7cpvrgjxvaj3lzn2tr34cu2lphoc

**Comment by kevzak** [comment]
@liyunzhi-666 any luck here? It might work for you now. 

Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@MatrixStorage
@Fenbushi-Filecoin

Please review application details above and note that this applicant passed the KYC/KYB requirements for E-Fil. Please comment by March 28th. Thanks!

**Comment by liyunzhi-666** [comment]
There was a problem with SSAbot before. Do I need to sign again? @kevzak 

> @liyunzhi-666 any luck here? It might work for you now.
> 
> Let's move forward with the update notary SLA ([filecoin-project/notary-governance#807](https://github.com/filecoin-project/notary-governance/discussions/807)) and assign randomly:
> 
> @MatrixStorage @Fenbushi-Filecoin
> 
> Please review application details above and note that this applicant passed the KYC/KYB requirements for E-Fil. Please comment by March 28th. Thanks!

**Comment by kevzak** [comment]
> There seems to be a problem with SSAbot before. Do I need to sign again? @kevzak
> 
> > @liyunzhi-666 any luck here? It might work for you now.
> > Let's move forward with the update notary SLA ([filecoin-project/notary-governance#807](https://github.com/filecoin-project/notary-governance/discussions/807)) and assign randomly:
> > @MatrixStorage @Fenbushi-Filecoin
> > Please review application details above and note that this applicant passed the KYC/KYB requirements for E-Fil. Please comment by March 28th. Thanks!

it's all good @liyunzhi-666, I see your proposal above, sorry for any confusion there.

**Comment by kevzak** [comment]
Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@xingjitansuo
@swatchliu

Please review application details above and note that this applicant passed the KYC/KYB requirements for E-Fil. Please comment by April 1st. Thanks!

**Comment by kevzak** [comment]
Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@jamerduhgamer
@PluskitOfficial


Please review application details above and note that this applicant passed the KYC/KYB requirements for E-Fil. Please comment by April 4th. Thanks!

**Comment by PluskitOfficial** [comment]
Everything looks OK. Willing to support.

**Comment by kevzak** [comment]
@PluskitOfficial haven't heard back from you

Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@Casey-PG
@laurarenpanda

Please review application details above and note that this applicant passed the KYC/KYB requirements for E-Fil. Please comment by April 6th. Thanks!

**Comment by kevzak** [comment]
@PluskitOfficial check it now, labels are updated

**Comment by laurarenpanda** [comment]
The Check report looks excellent.
Nothing unusual has been found at the moment.
Happy to support this round.

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced72jthln3ggqyjxrotu5lzkk5liuli7lxcsv2d363t25urebcz56 
#### Address 
> f1nt3mihrazsft66v6zgcyru2k45i3kjdufwujkia
#### Datacap Allocated
> 51.19TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced72jthln3ggqyjxrotu5lzkk5liuli7lxcsv2d363t25urebcz56

**Comment by jamerduhgamer** [comment]
Application and report also looks fine on our end. Approving the first round.

**Comment by jamerduhgamer** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzjefftzpdbv6tq4ginoetztkczkhfdqglpeloef4hzbjblhtmya 
#### Address 
> f1nt3mihrazsft66v6zgcyru2k45i3kjdufwujkia
#### Datacap Allocated
> 51.19TiB
#### Signer Address
> f1ypuqpi4xn5q7zi5at3rmdltosozifhqmrt66vhq
#### Id
> 2d0c662e-ee82-4ae9-9e9e-9d664ed343d3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzjefftzpdbv6tq4ginoetztkczkhfdqglpeloef4hzbjblhtmya

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebx6pznorswzg6mmhphc7b3dtbv2yv6utny3cz4vpfymmmnogccag 
#### Address 
> f1nt3mihrazsft66v6zgcyru2k45i3kjdufwujkia
#### Datacap Allocated
> 102.39TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebx6pznorswzg6mmhphc7b3dtbv2yv6utny3cz4vpfymmmnogccag

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
hey @FILDCKabat ,can you explain these three warnings?
⚠️ 1 storage providers sealed more than 30% of total datacap - [f01127678](https://filfox.info/en/address/f01127678): 52.55%
⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.
⚠️ CID sharing has been observed. (Top 3)

2.06 TiB - [f1ieughpsgkdynelb2tipfpuhdvcvltfvsuv54q2q](https://filfox.info/en/address/f1ieughpsgkdynelb2tipfpuhdvcvltfvsuv54q2q) - https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/928

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by FILDCKabat** [comment]
we will comeback

**Comment by jamerduhgamer** [comment]
Between June 3rd and July 8th, client has made efforts to involve more SPs (from 1 -> 4).

Just one question before I sign, the report says that there are ~173 TiBs of CIDs that are shared with your other application at #928. Is this a known issue that has already been explained somewhere?

**Comment by jamerduhgamer** [comment]
Hi @donkabat, thank you for the explanation. Willing to sign this LDN as long as the CID sharing % does not increase too much.

**Comment by jamerduhgamer** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec727jjsk5o3wm5xzuamvmgj2t5rtlkkjwf7amigynlum6suygcra 
#### Address 
> f1nt3mihrazsft66v6zgcyru2k45i3kjdufwujkia
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ypuqpi4xn5q7zi5at3rmdltosozifhqmrt66vhq
#### Id
> 91603d71-3f11-4375-993a-2d0c2dfa49d6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec727jjsk5o3wm5xzuamvmgj2t5rtlkkjwf7amigynlum6suygcra

**Comment by BlockMakeronline** [comment]
Hopefully, you can avoid such mistakes in the future.
I am willing to support it.

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblq5kdwsbrrlvlnvpmz4nhcdo6vi6es3rbd3ziatzrok4xl6guha 
#### Address 
> f1nt3mihrazsft66v6zgcyru2k45i3kjdufwujkia
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### Id
> 91603d71-3f11-4375-993a-2d0c2dfa49d6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblq5kdwsbrrlvlnvpmz4nhcdo6vi6es3rbd3ziatzrok4xl6guha

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
please explain why there is deal sharing with #928

**Comment by marshyonline** [comment]
@Joss-Hua https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1596#issuecomment-1668646714

**Comment by FILDCKabat** [comment]
comment

**Comment by FILDCKabat** [comment]
up

**Comment by FILDCKabat** [comment]
up

**Comment by Sunnyiscoming** [comment]
Hello, @FILDCKabat  per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by FILDCKabat** [comment]
> Hello, @FILDCKabat per the [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

Are You serious about that? all data which You want us to fill in You have already got moooonths ago.

**Comment by kevzak** [comment]
> > Hello, @FILDCKabat per the [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> > This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
> 
> Are You serious about that? all data which You want us to fill in You have already got moooonths ago.

disregard @FILDCKabat - that message is meant for non-E-FIl applications. Yours is okay

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
Can you explain more about that ⬆️ 0.0

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrrqevutzkekmmip5comswvuftxyfesr2t6cazvfscrtzam7ud6m 
#### Address 
> f1nt3mihrazsft66v6zgcyru2k45i3kjdufwujkia
#### Datacap Allocated
> 470.42TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 4afea8f3-e7c4-4470-a080-eea3a8632d60
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrrqevutzkekmmip5comswvuftxyfesr2t6cazvfscrtzam7ud6m

**Comment by cryptowhizzard** [comment]
@donkabat 

Nice to see real data onboarded on the network. Keep it going ;-)

**Comment by PluskitOfficial** [comment]
checker:manualTrigger

**Comment by FILDCKabat** [comment]
@marshyonline @jamerduhgamer @cryptowhizzard @fabriziogianni7 @liyunzhi-666 @Kevin-FF-USA @dkkapur @kevzak

**Comment by jamerduhgamer** [comment]
Unfortunately I shouldn't sign again since I signed the previous data cap tranche. Willing to support the next one though.

**Comment by Destore2023** [comment]
checker:manualTrigger

**Comment by Destore2023** [comment]
Based on the result of filplus checker bot, unfortunately I shouldn't approve this LDN. 

Why E-FIL+ got CID sharing?

**Comment by Carohere** [comment]
That explanation really doesn't convince me, plus your understanding of E-Fil retrieval seems to be controversial.

**Comment by Holiday507** [comment]
Thank you for your invitation, but I can't seem to approve your question until the issue in dispute is resolved.

**Comment by FILDCKabat** [comment]
@jamerduhgamer another one, the same issue

**Comment by jamerduhgamer** [comment]
checker:manualTrigger

**Comment by jamerduhgamer** [comment]
f02770730 seems to have a lot of the datacap. Would like to see this number lowered.

Also, looks like there needs to be more SPs onboarded.

Willing to support for now and continue monitoring the datacap usage.

**Comment by jamerduhgamer** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearofshykmo6f4i36cg5xiofqmlaz65qfhh366gluckq3thh3fcze 
#### Address 
> f1nt3mihrazsft66v6zgcyru2k45i3kjdufwujkia
#### Datacap Allocated
> 470.42TiB
#### Signer Address
> f1ypuqpi4xn5q7zi5at3rmdltosozifhqmrt66vhq
#### Id
> 4afea8f3-e7c4-4470-a080-eea3a8632d60
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearofshykmo6f4i36cg5xiofqmlaz65qfhh366gluckq3thh3fcze

**Comment by Sunnyiscoming** [comment]
Please provide ID, City, Country, Organization of each SP here.

**Comment by FILDCKabat** [comment]
up

**Comment by FILDCKabat** [comment]
> Please provide ID, City, Country, Organization of each SP here.

done

**Comment by FILDCKabat** [comment]
up

**Comment by FILDCKabat** [comment]
up

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
